# fly.toml app configuration file generated for reddit-admin on 2023-06-18T03:43:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reddit-admin"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
